# Generated by Django 4.0.6 on 2022-08-10 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='date_submit',
        ),
    ]
